/*

1 - LOGAR COM A CONTA usrdbaassists
2 - EXECUTAR O SCRIPT DE CREATE DATABASE ABAIXO
3 - O ERRO ABAIXO SERÁ APRESENTADO

Msg 262, Level 14, State 1, Line 3
CREATE DATABASE permission denied in database 'master'.

*/

CREATE DATABASE [DBDBAASSISTS2]

/*

1 - LOGAR COM CONTA DE PERMISSÃO DE ADMIN
2 - CONCEDER A PERMISSÃO CREATE DATABASE
3 - TESTAR A EXECUÇÃO DO SCRIPT ABAIXO COM A CONTA usrdbaassists

*/

ALTER SERVER ROLE [dbcreator] ADD MEMBER [usrdbaassists]
GO

GRANT CREATE ANY DATABASE TO [usrdbaassists]
GO