--DECLARE @FUNCIONARIO 
--TABLE
--(
--CODFUNCIONARIO INT
--, NOMEFUNCIONARIO VARCHAR(100)
--, DATANASCIMENTO DATETIME
--, NUMTELEFONE VARCHAR(11)
--)

--INSERT INTO @FUNCIONARIO (CODFUNCIONARIO, NOMEFUNCIONARIO, DATANASCIMENTO,NUMTELEFONE) 
--VALUES
--(1, 'GABRIEL' , '19811114','21987654321')
--,(2, 'JOSE', '19750529','11912345678')
--,(3 , 'PAULO', '20011205',NULL)

--SELECT CODFUNCIONARIO, NOMEFUNCIONARIO, DATANASCIMENTO,ISNULL(NUMTELEFONE,'11111111111') NUMTELEFONE FROM @FUNCIONARIO




SET LANGUAGE 'ENGLISH'

DECLARE @VENDA 
TABLE
(
CODVENDA INT
,NOMPRODUTO VARCHAR(100)
, QTDTOTAL INT
, VALOR DECIMAL(23,2)
, QTDVENDA INT
, UNDMED VARCHAR(2)
)

INSERT INTO @VENDA (NOMPRODUTO, QTDTOTAL, VALOR,QTDVENDA, UNDMED) 
VALUES
('WHISKY' , 1000,'250', 500,'ML')
,('CACHAÇA',1000, '69', 0,'ML' )
,('VINHO', 1000, '120', 500,'ML')

--SELECT NOMPRODUTO, QTDTOTAL, VALOR,QTDVENDA, UNDMED
--FROM @VENDA

--SELECT NOMPRODUTO, QTDTOTAL, VALOR,QTDVENDA, UNDMED, VALOR/(QTDTOTAL/QTDVENDA)
--FROM @VENDA


SELECT NOMPRODUTO, QTDTOTAL, VALOR,QTDVENDA, UNDMED, ISNULL(VALOR/(QTDTOTAL/NULLIF(QTDVENDA,0)),0) VLRVENDA 
FROM @VENDA





--SELECT SUBSTRING('DBAASSISTS',1,3)







--DECLARE @A VARCHAR(100)  = 'É MUITO ',
--		@B VARCHAR(100)  = 'BOM ',
--		@C VARCHAR(100)  = 'ESTUDAR DB ',
--		@D VARCHAR(100)  = 'COM A DBAASSISTS!'

--SELECT CONCAT(@A, @B, @C, @D) RETORNO


--DECLARE @A VARCHAR(100)  = 'É MUITO ',
--		@B VARCHAR(100)  = NULL,
--		@C VARCHAR(100)  = 'ESTUDAR DB ',
--		@D VARCHAR(100)  = 'COM A DBAASSISTS!'

--SELECT @A + ISNULL(@B,'') + @C + @D RETORNO



--DECLARE @A VARCHAR(100)  = 'TESTE FUNÇÃO',
--		@B VARCHAR(100)  = 'SPACE()',
--		@C VARCHAR(100)  = 'SPACE()'
--SELECT @A + SPACE(2) + @B + SPACE(10) + @C



--DECLARE @CODIGOCLIENTE VARCHAR(100)  = '12345'

--SELECT REPLICATE('0',2) + @CODIGOCLIENTE

DECLARE @A VARCHAR(100)  = 'DBAASSISTS'

SELECT SUBSTRING(@A,1,3) RETORNO

