/*

PRECISAMOS MONTAR UM SCRIPT PARA REALIZAR A SEGUINTE OPERAÇÃO:

UMA LOJA DE DEPARTAMENTO ESTÁ PRECISANDO CRIAR UM SISTEMA PARA REALIZAR CADASTRO DE SEUS CLIENTES E DE
ALGUMA FORMA DE REGISTRAR TODAS AS VENDAS REALIZADAS.

CIRAR UM CLIENTE COM O NOME 'CLIENTE NÃO IDENTIFICADO'
OS SEUS CLIENTES PODEM SER CADASTRADOS OU NÃO, ISSO NÃO É UMA REGRA;
ANTES DE CADASTRAR O CLIENTE, O SISTEMA PRECISA IDENTIFICAR SE ELE EXISTE NO CADASTRO;
CASO UM CLIENTE TENHA SEU CADASTRO REALIZADO, ELE PODE TER ALGUM TIPO DE DESCONTO EM SUAS COMPRAS;
ANTES DE FINALIZAR UMA VENDA, DEVERÁ VERIFICAR SE O PRODUTO SELECIONADO POSSUI A QUANTIDADE EM ESTOQUE;

*/

DECLARE 

@CLIENTE VARCHAR(100)
,@CADASTRO INT -- 1 PARA CADASTRAR / 0 PARA NÃO CADASTRAR
,@CODIGOPRODUTO INT
,@QUANTIDADE INT
,@CODIGOCLIENTE INT
,@QANTIDADEPRODUTOESTOQUE INT


SET @CLIENTE = 'GABRIEL'
SET @CADASTRO = 0
SET @CODIGOPRODUTO = 3
SET @QUANTIDADE = 2

IF @CLIENTE <> 'CLIENTE NÃO IDENTIFICADO' AND @CADASTRO = 1

BEGIN 

PRINT('PASSO 01')

	SELECT @CODIGOCLIENTE = clt.[CodigoCliente]
	FROM [dbo].[Tb_Cliente] clt
	WHERE clt.[NomeCliente] = @CLIENTE

	IF @CODIGOCLIENTE IS NULL

	BEGIN 

		INSERT INTO [dbo].[Tb_Cliente]  
		VALUES(@CLIENTE) 
		PRINT('CADASTRO REALIZADO DO CLIENTE')

		SELECT @CODIGOCLIENTE = clt.[CodigoCliente]
		FROM [dbo].[Tb_Cliente] clt
		WHERE clt.[NomeCliente] = @CLIENTE

	END 

	SELECT @QANTIDADEPRODUTOESTOQUE = [QuantidadeProduto]
	FROM [dbo].[Tb_Produto]
	WHERE [CodigoProduto] = @CODIGOPRODUTO

	IF @QANTIDADEPRODUTOESTOQUE >= @QUANTIDADE

	BEGIN

		PRINT('QUANTIDADE EM ESTOQUE')

		INSERT INTO [dbo].[Tb_Venda]
		([CodigoProduto],[CodigoCliente],[QuantidadeProduto])
		VALUES
		(@CODIGOPRODUTO,@CODIGOCLIENTE,@QUANTIDADE)

		UPDATE [dbo].[Tb_Produto]
		SET [QuantidadeProduto] = (@QANTIDADEPRODUTOESTOQUE - @QUANTIDADE)
		WHERE [CodigoProduto] = @CODIGOPRODUTO

	END 

	ELSE 

		PRINT('NÃO EXISTE MAIS ESSA QUANTIDADE EM ESTOQUE')

END 

ELSE 

BEGIN

PRINT('PASSO 02')

	SELECT @CODIGOCLIENTE = clt.[CodigoCliente]
	FROM [dbo].[Tb_Cliente] clt
	WHERE clt.[NomeCliente] = 'CLIENTE NÃO IDENTIFICADO'

	SELECT @QANTIDADEPRODUTOESTOQUE = [QuantidadeProduto]
	FROM [dbo].[Tb_Produto]
	WHERE [CodigoProduto] = @CODIGOPRODUTO

	IF @QANTIDADEPRODUTOESTOQUE >= @QUANTIDADE

	BEGIN

		PRINT('QUANTIDADE EM ESTOQUE')

		INSERT INTO [dbo].[Tb_Venda]
		([CodigoProduto],[CodigoCliente],[QuantidadeProduto])
		VALUES
		(@CODIGOPRODUTO,@CODIGOCLIENTE,@QUANTIDADE)

		UPDATE [dbo].[Tb_Produto]
		SET [QuantidadeProduto] = (@QANTIDADEPRODUTOESTOQUE - @QUANTIDADE)
		WHERE [CodigoProduto] = @CODIGOPRODUTO

	END 

	ELSE 

		PRINT('NÃO EXISTE MAIS ESSA QUANTIDADE EM ESTOQUE')

END

SELECT * FROM [dbo].[Tb_Produto] 
SELECT * FROM [dbo].[Tb_Venda]