DROP TABLE dbo.TB_VEICULO

CREATE TABLE dbo.TB_VEICULO
(
ID INT NOT NULL PRIMARY KEY,
NMVEICULO VARCHAR(100),
IDMONTADORA INT
)

INSERT INTO dbo.TB_VEICULO (ID, NMVEICULO, IDMONTADORA) VALUES ( 1,'FUSCA',1)
INSERT INTO dbo.TB_VEICULO (ID, NMVEICULO, IDMONTADORA) VALUES ( 2,'CHEVETTE',3)
INSERT INTO dbo.TB_VEICULO (ID, NMVEICULO, IDMONTADORA) VALUES ( 3,'BRASILIA',1)
INSERT INTO dbo.TB_VEICULO (ID, NMVEICULO, IDMONTADORA) VALUES ( 4,'FIAT 147',2)
INSERT INTO dbo.TB_VEICULO (ID, NMVEICULO, IDMONTADORA) VALUES ( 5,'KOMBI',1)
INSERT INTO dbo.TB_VEICULO (ID, NMVEICULO, IDMONTADORA) VALUES ( 6,'OPALA',3)
INSERT INTO dbo.TB_VEICULO (ID, NMVEICULO, IDMONTADORA) VALUES ( 7,'CITROEN C4',NULL)

DROP TABLE dbo.TB_MONTADORA

CREATE TABLE dbo.TB_MONTADORA
(
ID INT NOT NULL PRIMARY KEY,
MONTADORA VARCHAR(100)
)

INSERT INTO dbo.TB_MONTADORA (ID, MONTADORA) VALUES (1, 'VOLKSVAGEM')
INSERT INTO dbo.TB_MONTADORA (ID, MONTADORA) VALUES (2, 'FIAT')
INSERT INTO dbo.TB_MONTADORA (ID, MONTADORA) VALUES (3, 'CHEVROLET')
INSERT INTO dbo.TB_MONTADORA (ID, MONTADORA) VALUES (4, 'MERCEDES-BENZ')


SELECT VEI.ID, VEI.NMVEICULO, MONT.MONTADORA
FROM dbo.TB_VEICULO VEI
RIGHT JOIN dbo.TB_MONTADORA MONT
ON VEI.IDMONTADORA = MONT.ID
WHERE VEI.IDMONTADORA IS NULL

