

DECLARE @VARIAVEL INT 
SET @VARIAVEL = 1
SELECT @VARIAVEL VALORVARIAVEL

DECLARE @SOMA INT , @VALOR1 INT , @VALOR2 INT
SET @VALOR1 = 1
SET @VALOR2 = 2
SET @SOMA = @VALOR1 + @VALOR2
SELECT @SOMA VALORSOMA

DECLARE @NOME VARCHAR(100)

SELECT @NOME = [primeiro_nome]
FROM [dbo].[empregados]
WHERE codigo_empregado = 1

SELECT @NOME PRIMEIRO_NOME



