SET LANGUAGE 'ENGLISH'

/*

1 - LOGAR COM O USUARIO usrrelatorio 
2 - EXECUTAR O SCRIPT ABAIXO PARA VALIDAR QUE REALMENTE O USUARIO usrrelatorio SÓ POSSUI ACESSO AO SCHEMA dbaassists

*/

SELECT * FROM [dbo].[Funcionario]